// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// r2_subset_cpp
NumericMatrix r2_subset_cpp(NumericMatrix G, IntegerVector candidate_idx);
RcppExport SEXP _OptSLDP_r2_subset_cpp(SEXP GSEXP, SEXP candidate_idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type G(GSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type candidate_idx(candidate_idxSEXP);
    rcpp_result_gen = Rcpp::wrap(r2_subset_cpp(G, candidate_idx));
    return rcpp_result_gen;
END_RCPP
}
// above_threshold_subset_cpp
IntegerMatrix above_threshold_subset_cpp(NumericMatrix R2, double threshold, bool exclude_diag);
RcppExport SEXP _OptSLDP_above_threshold_subset_cpp(SEXP R2SEXP, SEXP thresholdSEXP, SEXP exclude_diagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type R2(R2SEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type exclude_diag(exclude_diagSEXP);
    rcpp_result_gen = Rcpp::wrap(above_threshold_subset_cpp(R2, threshold, exclude_diag));
    return rcpp_result_gen;
END_RCPP
}
// greedy_prune_r2_cpp
LogicalVector greedy_prune_r2_cpp(const NumericMatrix& r2_mat, const double threshold);
RcppExport SEXP _OptSLDP_greedy_prune_r2_cpp(SEXP r2_matSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type r2_mat(r2_matSEXP);
    Rcpp::traits::input_parameter< const double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(greedy_prune_r2_cpp(r2_mat, threshold));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_OptSLDP_r2_subset_cpp", (DL_FUNC) &_OptSLDP_r2_subset_cpp, 2},
    {"_OptSLDP_above_threshold_subset_cpp", (DL_FUNC) &_OptSLDP_above_threshold_subset_cpp, 3},
    {"_OptSLDP_greedy_prune_r2_cpp", (DL_FUNC) &_OptSLDP_greedy_prune_r2_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_OptSLDP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
