# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

r2_subset_cpp <- function(G, candidate_idx) {
    .Call(`_OptSLDP_r2_subset_cpp`, G, candidate_idx)
}

above_threshold_subset_cpp <- function(R2, threshold, exclude_diag = TRUE) {
    .Call(`_OptSLDP_above_threshold_subset_cpp`, R2, threshold, exclude_diag)
}

greedy_prune_r2_cpp <- function(r2_mat, threshold) {
    .Call(`_OptSLDP_greedy_prune_r2_cpp`, r2_mat, threshold)
}

